# Utilise l'image Nginx comme base
FROM nginx:alpine

# Copier les fichiers générés par ng build dans le répertoire de l'image Nginx
COPY dist/jap /usr/share/nginx/html

# Copier le fichier de configuration Nginx
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

# Exposer le port utilisé par Nginx (généralement 80)
EXPOSE 80

# Commande pour démarrer Nginx
CMD ["nginx", "-g", "daemon off;"]
